### ISSUE TITLE
How can a DinD solution like this be 'secure'?

### ISSUE THREAD

**Issue by tobilarscheid** [franela/play-with-docker#123]
Hi guys,

saw the awesome presentation of this project on DockerCon, thanks a lot!!

One thing I can not quite get my head wrapped around is this:

If this whole thing is based on Docker in Docker, how do you isolate one user's sessions from all other running sessions? I assume that everytime I click "create new session", a `--privileged` container is created. (Otherwise DinD would not work, this line in the code seems to prove what I am assuming: https://github.com/franela/play-with-docker/blob/6acb6f47c556cced54e2ac5de8212adc8d73e2cb/services/docker.go#L203 )

Thanks in advance for your explanation,

Regards,

Tobi

**Comment by CarltonSemple** [comment]
I was also wondering about this. Are you using Linux containers?

**Comment by xetorthio** [comment]
Hi! Users sessions are not perfectly isolated. We have a few apparmor
policies in place and have tweaked the host machine to disallow some
obvious, and not so obvious, 'bad behaviour'. But since DinD requires
containers to be privileged perfect isolation is hard, maybe impossible.
But also it is not the point. This is a playground. The environment is
expected not to be secure, which means people shouldn't expose any
sensitive data (we are going to add a very explicit message regard this).
That being said, if you have any suggestions on how to improve isolation,
without making the whole thing slower and cumbersome, it will be more than
welcome.

Hope this clarify a little.

**Comment by CarltonSemple** [comment]
@xetorthio thanks! Yes, that does make sense as it's not meant for serious usage.

**Comment by xetorthio** [comment]
Btw, for a more secure/isolated thing you can download PWD and run it on your own instances. We know a few people that are doing it in their companies, as an internal and private docker playground.

**Comment by xetorthio** [comment]
Closing this for now. We can re-open in case there is more to discuss :)

**Comment by AkihiroSuda** [comment]
Rootless mode (expected to be merged soon) can be used for isolating DinD per user: https://github.com/moby/moby/pull/38050
