### ISSUE TITLE
Add support for terminal resize

### ISSUE THREAD

**Issue by marcosnils** [franela/play-with-docker#16]
Current terminal size is hardcoded to a default size of 80 x 24. It'd be nice to automatically handle  screen resize. 

I believe this should be implemented after #10 to prevent any possible re-work.

**Comment by akalipetis** [comment]
In order to refit the Terminal, the [`fit`](https://github.com/sourcelair/xterm.js/blob/master/addons/fit/fit.js) addon should be used. The `.fit()` function should be called to update the geometry of the Terminal, every time the container of the Terminal changes size, ie after a window resize.

Apart from that, the update in rows/lines should be also sent to the backend, to update the TTY of the container. This can be done using the [`resize`](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/resize-a-container-tty) API call each time a [`resize`](https://github.com/sourcelair/xterm.js/blob/master/src/xterm.js#L2949) event is emitted.

**Comment by xetorthio** [comment]
Done!
