### ISSUE TITLE
Store state on disk

### ISSUE THREAD

**Issue by xetorthio** [franela/play-with-docker#20]
We can store all session information on disk so whenever we restart the API, we can still have all the sessions.
**We need to check if there is something we can do to not loose our terminals.**

**Comment by marcosnils** [comment]
> We need to check if there is something we can do to not loose our terminals.

#23 

Another thing that we discussed is that we'll have to change the way that the sessions are being expired. Basically the ticker will have to check against the session creation date instead of being hardcoded as it is today. 

This is better because we have a single timer that handles all the sessions invalidations.

**Comment by marcosnils** [comment]
Done :tada: 

#32
