### ISSUE TITLE
Access service from public internet with ngrok

### ISSUE THREAD

**Issue by alexellis** [franela/play-with-docker#3]
I tried running ngrok but it crashed the screen and gave an error about $HOME.. this would be really cool for connecting to the live service from your PC.

👍 on this project.. very cool proof of concept 💯 %

**Comment by xetorthio** [comment]
Hey Alex, can you describe with more details what you are doing? Where are
you running ngrok? How? Etc.

**Comment by xetorthio** [comment]
A bit more of information before my flight :) It seems like ngrok works fine. But it writes its output directly to the terminal, which is not shown on the web interface because only Stdout and Stderr are captured. 
So the way to make it show what it is doing is to add `--log stdout` so it outputs to Stdout, hence visible on the web ui.

Now I'm trying to figure out which url I should connect to see my elasticsearch service 😕

**Comment by marcosnils** [comment]
@alexellis I think we've fixed this issue with @xetorthio in 3dd5a8b5ef48405fb1e5164132fd08045e3a30d9. Can you please try again to see if it works?

**Comment by akalipetis** [comment]
Would we be interested in dynamically proxying ports - ie 30000-30005 - to something like <session-id>-<port>.play-with-docker.com?

We could use [sourcelair/ceryx](https://github.com/sourcelair/ceryx) for that.

There are a few challenges though:

* Ceryx currently only supports one target for each domain
    * we can circumvent this by proxying requests only to the first engine we create
    * we could try to do a Docker networking/load balancing trick, but this means that all containers will be able to hit each other
* we should limit the ports, since we'll need to expose them in advance
    * this will not be the case though if we move to a Docker networking solution, but we'll need the user to manually define which ports she wants to expose to create the route

Thoughts?

**Comment by marcosnils** [comment]
@akalipetis does ceryx also supports proxying plain tcp connections?

**Comment by akalipetis** [comment]
Nope, Ceryx is layer 7... I don't think we'll be able to somehow do this
though. Best thing I can think of is forward a random port to the container
port, like Docker does.

**Comment by marcosnils** [comment]
@akalipetis ngrok works both for L4 and L7 connections so I believe that we can go that way. I'll close this issue as it's fixed already.
