### ISSUE TITLE
Unable to access PWD host/cluster via Portainer

### ISSUE THREAD

**Issue by deviantony** [franela/play-with-docker#93]
Usually, I connected Portainer to PWD either when starting Portainer via the CLI with the `-H` flag or via the UI by defining a new endpoint.

I used to manage the PWD endpoints using the following url pattern `ip10_0_XX_XX-2375.play-with-docker.com:80`.

Example:

```
$ docker run -d -p 9000:9000 portainer/portainer -H tcp://ip10_0_XX_XX-2375.play-with-docker.com:80
```

Yesterday, when I tried it again I was not able to connect to PWD either from Portainer or via the CLI using this URL pattern. After a short discussion on twitter with @marcosnils (https://twitter.com/marcosnils/status/831108149860036608), he told me to update the URL pattern to `ip10_0_XX_XX.play-with-docker.com`.

Now, this is working fine when I use the Docker CLI with the `-H` flag but it's not working anymore with Portainer (either using the `-H` flag or when defining the endpoint from the UI).

Portainer tries to proxy the request to the PWD host/cluster and gets a 502 Bad Gateway issue.

**Comment by marcosnils** [comment]
@deviantony the problem is that portainer is making requests to PWD with the `host` header set as `localhost:9000` when running locally.

here's a tcpdump capture of the `info` request portainer does 
```
..GET /info HTTP/1.1
Host: localhost:9000
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/55.0.2883.87 Chrome/55.0.2883.87 Safari/537.36
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8,pt-BR;q=0.6,pt;q=0.4,es;q=0.2,nb;q=0.2
Referer: http://localhost:9000/
X-Forwarded-For: ::1
```
You need to make sure that `Host` header is set to the PWD endpoint in order for it to work. I believe that's a problem with the portainer proxy. We made a change that relies on the `Host` sent by the caller in PWD and in this case an incorrect header is being sent.

**Comment by deviantony** [comment]
Thanks for the update ! Have these changes related to the `Host` added recently ? Because it was working 2 weeks ago.

**Comment by marcosnils** [comment]
Yes, we deployed some changes regarding the Host header.

sent from mobile
